### PR TITLE
Reduce clock jitter and support 100MHz SYSCLK.

### PR DESCRIPTION
**Pull request by matsujirushi**

### CODE REVIEW

**Comment by Arke64** [comment]
Can you give a brief explanation on the purpose of this PR?

A quick note on something I saw: you set the PLLQ bits to VCO_OUT / 48MHz. In the WiFiMCU device, VCO_OUT is 200MHz which truncates to a divisor of 4, actually giving a clock of 50MHz. That's not the 48MHz required by USB OTG FS and is more than the 48MHz allowed by SDIO, according to the caution note in 6.3.2, bits 27:24, of RM0383. So that clock selection seems like it'll prevent both USB and SDIO from working.

**Comment by matsujirushi** [comment]
Ok. :-)
We can't use USB-OTG and SDIO for WiFiMCU(EMW3165) because it not present i/o pins.

Please look the schematic:
https://github.com/SmartArduino/WiFiMCU/blob/master/Document/WiFiMCU_SCH.pdf

**Comment by Arke64** [comment]
Just wanted to be sure.

In your additions, do STM32F4_VCO_IN_CLOCK_HZ and STM32F4_VCO_OUT_CLOCK_HZ refer to the VCO input and output in the PLL mentioned in the formulas in the same section 6.3.2 from above in bits PLLN, PLLM, and PLLP?

**Comment by Arke64** [comment]
If so, I think the better solution than to manually providing those values is to calculate PLLQ separately and remove the % 48000000 check when calculating PLLM, PLLN, and PLLP. We can then add a define, `STM32F4_PLLQ_48_OVERRIDE` that will allow PLLQ to produce an invalid configuration. We can add a check in the USB client and future SDIO code that errors when the above define is present.

**Comment by matsujirushi** [comment]
> In your additions, do STM32F4_VCO_IN_CLOCK_HZ and STM32F4_VCO_OUT_CLOCK_HZ refer to the VCO input and output in the PLL mentioned in the formulas in the same section 6.3.2 from above in bits PLLN, PLLM, and PLLP?

Yes. I am reffering to Figure 12. Clock tree on P92.

>  I think the better solution than to manually providing those values is to calculate PLLQ separately

Sorry, I can't understand because I can only read English little...
Could you tell me define sample code?

**Comment by Arke64** [comment]
Sure. I'd get rid of the `STM32F4_VCO_IN_CLOCK_HZ` and `STM32F4_VCO_OUT_CLOCK_HZ` defines and then add `STM32F4_PLLQ_48_OVERRIDE` as a define in WiFiMCU/Device.h.

Then in STM32F4_Startup.cpp, undo your changes and instead, starting on the old line 63 and on to line 91, remove `&& (STM32F4_SYSTEM_CLOCK_HZ * 2 % 48000000 == 0)`. In the follow #elif blocks, replace the five instances of `#define RCC_PLLCFGR_PLLQ_BITS` with a single integer defining the scale factor. For example:

```c
#if (STM32F4_SYSTEM_CLOCK_HZ * 2 >= 192000000)\
 && (STM32F4_SYSTEM_CLOCK_HZ * 2 <= 432000000)
 //Remove: && (STM32F4_SYSTEM_CLOCK_HZ * 2 % 48000000 == 0)
    #define RCC_PLLCFGR_PLLM_BITS (STM32F4_EXT_CRYSTAL_CLOCK_HZ / ONE_MHZ * RCC_PLLCFGR_PLLM_0)
    #define RCC_PLLCFGR_PLLN_BITS (STM32F4_SYSTEM_CLOCK_HZ * 2 / ONE_MHZ * RCC_PLLCFGR_PLLN_0)
    #define RCC_PLLCFGR_PLLP_BITS (0)  // P = 2
    //Remove: #define RCC_PLLCFGR_PLLQ_BITS (STM32F4_SYSTEM_CLOCK_HZ * 2 / 48000000 * RCC_PLLCFGR_PLLQ_0)
    //Add:
    #define RCC_PLLCFGR_PLLQ_SCALE 2
#elif
```

Then after that block add something like:

```c
#ifndef STM32F4_PLLQ_48_OVERRIDE
    #if STM32F4_SYSTEM_CLOCK_HZ * RCC_PLLCFGR_PLLQ_SCALE % 48000000 == 0
        #define RCC_PLLCFGR_PLLQ_BITS (STM32F4_SYSTEM_CLOCK_HZ * RCC_PLLCFGR_PLLQ_SCALE / 48000000 * RCC_PLLCFGR_PLLQ_0)
    #else
        #error illegal STM32F4_SYSTEM_CLOCK_HZ frequency
    #endif
#elif !defined(INCLUDE_USBCLIENT)
    #define RCC_PLLCFGR_PLLQ_BITS (STM32F4_SYSTEM_CLOCK_HZ * 2 / 48000000 * RCC_PLLCFGR_PLLQ_0)
#else
    #error Can't include USB client when defining STM32F4_PLLQ_48_OVERRIDE.
#endif
```

**Comment by matsujirushi** [comment]
Thank you for post code.

I think my code better than old code because it is easy to create device.h to define STM32F4_VCO_IN_CLOCK_HZ and STM32F4_VCO_OUT_CLOCK_HZ. But my code less check.

I think that I will increase the check logic on my code, what do you think?

**Comment by Arke64** [comment]
I think the general goal we should follow is that the user (those who create new devices and need to change `Device.h`) should need to do as little as possible. We should be able to calculate all intermediate clocks, multipliers, and dividers directly from the clocks the user says he needs for the system, AHB, and APB.

As far as I can tell, we can calculate the parameters needed for the 100MHz system, AHB, and APB2 clocks and the 50MHz APB1 clock as long as we're provided with the external crystal source. VCO_IN and VCO_OUT just make the user calculate something that we could calculate in the preprocessor.

**Comment by matsujirushi** [comment]
OK. I agree.
Close this pull request and create new request after new commit.
Thanks.

**Comment by Arke64** [comment]
Closing per above, will reference this in the new PR.

**Pull request closed without merging**
